---
- name: Converge
  hosts: all
  vars:
    enable_worker_cronjobs: true
    enable_purge_cronjobs: true

    swap_device: /dev/vdb
    dlrn_server_type: 'server'
    enable_https: true
    dlrn_manage_letsencrypt: false
    dlrn_host: amoralej-trunk-server

    ip_trunk_server: 192.168.1.2
    ip_trunk_builder: 192.168.1.3

    web_domain: 'amoralej-trunk-server.rdoproject.org'

    api_workers:
      - centos9-caracal
    dlrn_manage_letsencrypt: false
    dlrn_workers:
      centos9-caracal:
        distro: 'centos9'
        target: 'centos9-caracal'
        distgit_branch: 'caracal-rdo'
        distro_branch: 'stable/2024.1'
        enable_cron: true
        enable_purge: "{{ enable_purge_cronjobs }}"
        purge_hour: '2'
        purge_minute: '17'
        symlinks: ['/var/www/html/centos9-caracal', '/var/www/html/caracal/centos9']
        release: 'caracal-uc'
        baseurl: 'https://trunk.rdoproject.org/centos9-caracal'
        pkginfo_driver: 'dlrn.drivers.rdoinfo.RdoInfoDriver'
        build_driver: 'dlrn.drivers.mockdriver.MockBuildDriver'
        db_connection: 'sqlite:///commits.sqliteabc'
        mock_tmpfs_enable: true
        fallback_to_master: true
        include_srpm_in_repo: true
        enable_deps_sync: true
        enable_brs_sync: true
        #gerrit_user: 'rdo-trunk'
        #gerrit_email: 'amoralej+rdo-trunk@redhat.com'
        #gerrit_topic: 'rdo-FTBFS-caracal-cs9'
        #rsyncdest: 'centos9-caracal@3.87.151.16:/home/centos9-caracal/data/repos'
        #rsyncport: '3300'
        #use_components: true
        rdoinfo_repo: 'http://github.com/redhat-openstack/rdoinfo'
        rdoinfo_info_files: 'test.yml'
        mock_config: 'centos9stream.cfg.j2'
        uid: 1011
        gid: 1012
  tasks:
    - name: Pre-install some packages
      package:
        name:
          - openssh-server
          - cronie

    - name: Create directory for SSL certificates
      file:
        path: "/etc/letsencrypt/live/{{ web_domain }}/"
        state: directory
        mode: '0755'

    - name: Deploy dummy SSL certificate
      copy:
        src: "{{ item }}"
        dest: "/etc/letsencrypt/live/{{ web_domain }}/{{ item }}"
        mode: 0640
      with_items:
        - cert.pem
        - fullchain.pem
        - privkey.pem

    - name: "Include dlrn"
      include_role:
        name: "dlrn"
