---
- job:
    name: dlrn-tox-molecule
    parent: tox-molecule
    pre-run: zuul/molecule-prepare.yml
    nodeset: rdo-centos-8
    timeout: 7200

- project:
    check:
      jobs:
        - tox-linters
        - dlrn-tox-molecule
    gate:
      jobs:
        - tox-linters
        - dlrn-tox-molecule
