---
- job:
    name: dlrn-tox-molecule
    parent: tox
    pre-run: zuul/molecule-prepare.yml
    run: zuul/molecule-run.yml
    nodeset: rdo-centos-9-stream
    timeout: 10800
    vars:
      tox_envlist: molecule


- project:
    check:
      jobs:
        - tox-linters
        - dlrn-tox-molecule
    gate:
      jobs:
        - tox-linters
        - dlrn-tox-molecule
