- name: Common DLRN deployment
  include_tasks: common.yml

- name: Prepare promoter user
  include_tasks: promoter.yml

- name: Configure rdoinfo user
  include_tasks: rdoinfo.yml

- name: Configure fail2ban
  include_tasks: fail2ban.yml

- name: Configure DLRN workers
  include_tasks: worker.yml
  loop: "{{ lookup('dict', dlrn_workers, wantlist=True) }}"
  loop_control:
    loop_var: worker

- name: Configure web server
  include_tasks: web.yml
