---
- name: Converge
  hosts: all
  vars:
    web_domain: trunk.rdoproject.org
    enable_https: false
    api_workers: []
    dlrn_manage_letsencrypt: false
  tasks:
    - name: Pre-install some packages
      package:
        name:
          - openssh-server
          - cronie

    - name: "Include dlrn"
      include_role:
        name: "dlrn"
