---
- hosts: all
  tasks:
    - name: Set required SELinux booleans on host
      seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      with_items:
        - container_manage_cgroup
      become: yes
