- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
