---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    registry: quay.io/centos
    image: centos:stream8
    command: "/sbin/init"
provisioner:
  name: ansible
verifier:
  name: testinfra
