---
- name: Converge
  hosts: all
  vars:
    dlrn_server_type: primary
    disable_worker_email: &disable_email true
    enable_worker_cronjobs: &enable_cron true
    enable_purge_cronjobs: &enable_purge false
    web_domain: trunk.rdoproject.org
    enable_https: false
    api_workers:
      - rhel8-master
      - centos8-train
      - centos-stein
      - centos8-master-uc
    dlrn_manage_letsencrypt: false
    dlrn_workers:
      centos8-train:
        distro: 'centos8'
        target: 'centos8-train'
        distgit_branch: 'train-rdo'
        distro_branch: 'stable/train'
        disable_email: *disable_email
        enable_cron: false
        enable_purge: true
        purge_hour: '3'
        purge_minute: '30'
        symlinks:
          - '/var/www/html/centos8-train'
          - '/var/www/html/train/centos8'
        release: 'train'
        baseurl: 'https://trunk.rdoproject.org/centos8'
        pkginfo_driver: 'dlrn.drivers.rdoinfo.RdoInfoDriver'
        build_driver: 'dlrn.drivers.mockdriver.MockBuildDriver'
        db_connection: 'sqlite:///commits.sqlite'
        mock_tmpfs_enable: true
        fallback_to_master: true
        include_srpm_in_repo: true
        enable_deps_sync: true
        enable_brs_sync: true
        gerrit_user: 'rdo-trunk'
        gerrit_email: 'javier.pena@redhat.com'
        gerrit_topic: 'rdo-FTBFS-train'
        rsyncdest: 'centos-master@backupserver.example.com:/home/centos-master/data/repos'
        rsyncport: '3000'
        use_components: true
        enable_public_rsync: false
      rhel8-master:
        distro: 'rhel8'
        target: 'rhel8'
        distgit_branch: 'rpm-master'
        distro_branch: 'master'
        disable_email: *disable_email
        enable_cron: *enable_cron
        enable_purge: *enable_purge
        purge_hour: '7'
        purge_minute: '7'
        symlinks: ['/var/www/html/rhel8-master', '/var/www/html/redhat8-master']
        release: 'wallaby-uc'
        baseurl: 'http://trunk.rdoproject.org/rhel8-master'
        pkginfo_driver: 'dlrn.drivers.rdoinfo.RdoInfoDriver'
        db_connection: 'sqlite:///commits.sqliteabc'
        mock_tmpfs_enable: false
        fallback_to_master: true
        include_srpm_in_repo: true
        enable_deps_sync: false
        enable_brs_sync: false
        enable_public_rsync: false
        rdoinfo_repo: 'http://github.com/redhat-openstack/rdoinfo'
        rdoinfo_info_files: 'test.yml'
      centos8-master-uc:
        distro: 'centos8'
        target: 'centos8-master-uc'
        distgit_branch: 'rpm-master'
        distro_branch: 'master'
        disable_email: *disable_email
        enable_cron: *enable_cron
        enable_purge: *enable_purge
        purge_hour: '2'
        purge_minute: '7'
        symlinks: ['/var/www/html/centos8', '/var/www/html/centos8-master']
        release: 'wallaby-uc'
        baseurl: 'https://trunk.rdoproject.org/centos8'
        pkginfo_driver: 'dlrn.drivers.rdoinfo.RdoInfoDriver'
        build_driver: 'dlrn.drivers.mockdriver.MockBuildDriver'
        db_connection: 'sqlite:///commits.sqlite'
        mock_tmpfs_enable: true
        fallback_to_master: true
        include_srpm_in_repo: true
        enable_deps_sync: false
        enable_brs_sync: false
        release_numbering: '0.date.hash'
        enable_public_rsync: true
        public_rsync_hosts_allow: ['dummy.example.com']
        mock_config: centos8stream.cfg.j2
      centos-stein:
        distro: 'centos7'
        target: 'centos-stein'
        distgit_branch: 'stein-rdo'
        distro_branch: 'stable/stein'
        disable_email: false
        enable_cron: *enable_cron
        enable_purge: *enable_purge
        cron_hour: '*'
        cron_minute: '12,42'
        purge_hour: '3'
        purge_minute: '37'
        symlinks: ['/var/www/html/centos7-stein', '/var/www/html/stein/centos7']
        release: 'stein'
        baseurl: 'https://trunk.rdoproject.org/centos7-stein'
        pkginfo_driver: 'dlrn.drivers.rdoinfo.RdoInfoDriver'
        db_connection: 'sqlite:///commits.sqlite'
        mock_tmpfs_enable: true
        fallback_to_master: true
        include_srpm_in_repo: true
        enable_deps_sync: true
        enable_brs_sync: true
        release_numbering: 'minor.date.hash'
        release_minor: '5'
        enable_public_rsync: true
        public_rsync_hosts_allow: ['dummy.example.com']
  tasks:
    - name: Pre-install some packages
      package:
        name:
          - openssh-server
          - cronie

    - name: "Include dlrn"
      include_role:
        name: "dlrn"
